spring.main.allow-bean-definition-overriding : false


#
spring:
  main:
    web-application-type: none
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:mysql://localhost:3306/spring_test?serverTimezone=Asia/Seoul
    url: jdbc:postgresql://localhost:5432/spring_test?serverTimezone=Asia/Seoul
    username: hanseung
    password: hanseung
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


# servlet의 포트 설정
server:
  port: 9000

#  ssl:
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 123456
#    key-alias: spring

logging:
  file:
    path: ./var/logs
  config: classpath:logback-${spring.profiles.active}.xml

---

hanseung:
  name: hanseung
  age: "${rndom.int(0,100)}" # " 는 있어도 되고 없어도 된다

---

holoman:
  name: "hanseung"
  how-long: 34

person:
  age: 34
  sex: "M"
  height: 180
  name: "hslee"

phone:
  os: "ios"
  series: 8

phone2:
  os: "android"
  series: 10